name: production
on:
  push:
    branches:
      - "production"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install modules
        run: npm i
      - name: Build application
        run: npm run build
      - name: Copy files
        run: cp -r dist/* /astro-converter
      - name: Run Python script
        run: python3 /astro-converter/index.py
      - name: Ceate release
        uses: softprops/action-gh-release@v1
        with:
          files: /astro-converter/output
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
